### ISSUE TITLE
Bulk Storage Tooltip

### ISSUE THREAD

**Issue by LasKru** [62832/MEGACells#10]
I would love to have a tooltip that shows how much is stored in the bulk storage cells. 
Additionally it would be awesome to see how much can be stored in those cells to be able to compare them to other storage options. 

Thank you for your work!

**Comment by 62832** [comment]
Hi, thank you for the suggestions!

You might notice that bulk cells at the moment are relatively simplistic in their implementation and that I've been trying for a while to rewrite them to have proper near-infinite capacity and functionality. This is likely going to come as part of that.

**Comment by 62832** [comment]
The tooltip has now been reworked as part of the larger overall rewrite of bulk cells.

![unknown-321](https://user-images.githubusercontent.com/5098830/194786621-efc034db-3903-4e25-b756-d52bddcde7d8.png)

![unknown-530](https://user-images.githubusercontent.com/5098830/194786615-71b8bc69-0c2f-4575-a613-32c211a084d3.png)
