### ISSUE TITLE
Idea: ME Bulk Fluid Cell

### ISSUE THREAD

**Issue by James103** [62832/MEGACells#105]
Functions identically to the ME Bulk Item Cell, except can store an infinite amount of a single fluid type.
Useful for fluids required in very large quantities, such as steam when using Modern Industrialization, Mekanism, or Extreme Reactors.

Crafting recipe would be similarly expensive to the ME Bulk Item Cell, but swap out one of the ingredients for a copper block.

**Comment by 62832** [comment]
Why wouldn't a regular 256M cell be enough for these fluids?

**Comment by James103** [comment]
I am closing this until I run into a real situation where I am bottlenecked by the amount of fluid I can store, despite having multiple 256M MEGA Cells dedicated to that fluid. That is,
* A crafting sequence required for progression requires more than 2 × 10<sup>12</sup> mB of a single fluid.
* A machine or process outputs more than 2 × 10<sup>12</sup> mB in a single operation.
* A machine or process outputs fluid at a rate that would fill a single 256M MEGA Fluid Cell in a few minutes or less, and that fluid can't simply be voided.
