### ISSUE TITLE
MEGA Source Cells appear to have 1/1024 of their intended capacities

### ISSUE THREAD

**Issue by James103** [62832/MEGACells#106]
As of MEGA Cells version 2.3.0 and Ars Énergistique version 1.1.5, the MEGA Source cells (1M and above) appear to have capacities which are 1/1024 of their intended values.

For example, while the Ars Énergistique ME 256k Source Cell can hold 25600 bytes of Source, the very next tier, MEGA 1M Source Cell, appears to only be able to hold 100 bytes, a 256x _decrease_ instead of the expected 4x increase.

This was originally found in All the Mods 9 version 0.2.46.

**Comment by 62832** [comment]
Can't believe I missed this. Thanks!
