### ISSUE TITLE
Mana Bulk Cells dont give correct Housing

### ISSUE THREAD

**Issue by micrwvae** [62832/MEGACells#107]
when popping out the storage component out of mega mana cells u get the me mana cell housing from applied botanistics instead of the mega mana housing used to craft the cell

mod versions:
applied energistics: 15.0.20
mega cells: 2.2.9-1.20.1
applied botanistics: 1.5.0

**Comment by 62832** [comment]
Ah, that's pretty annoying. I'll get to this ASAP.
