### ISSUE TITLE
[Feature Request] Self-partition card for MEGA Bulk Item Storage Cell

### ISSUE THREAD

**Issue by PaulMPomichter** [62832/MEGACells#108]
I was thinking it would be nice QOL to be able to opt into a mode with bulk item cells to partition themselves to the first item they happen to receive in an IO port or while installed in an ME Drive.

A use case would be: Make 100 bulk item cells, put them into drive bays with high priority, dump items into system and bulk cells partition themselves as they receive items (for the first 100 types that get dumped that is)

**Comment by 62832** [comment]
I really don't see what good this would do, given that any such cells would probably be receiving an item that there might not be much of and would just be wasteful to use a bulk cell on.
