### ISSUE TITLE
[1.20.4 NeoForge] CPU multi-block structure doesn't render properly when installed with Xaero's World Map

### ISSUE THREAD

**Issue by LittleCircleOO** [62832/MEGACells#117]
When installed with Xaero's World Map, the CPU multi-block structure does not render, but AE2's renders normally.
![issue](https://github.com/62832/MEGACells/assets/51949761/4403727b-b054-4b1b-983d-eea62c2cb844)
![issue2](https://github.com/62832/MEGACells/assets/51949761/9284e9cc-9363-41b8-b52b-2d9d2ace0803)
### Minecraft Version
1.20.4

### NeoForge Version
20.4.233

### Mod Version
AE2：17.13.0-beta
MEGACells：3.0.0
Xaero's World Map：1.38.4

**Comment by 62832** [comment]
Related: https://github.com/pedroksl/AdvancedAE/issues/57
