### ISSUE TITLE
What exactly is the Decompression Module?

### ISSUE THREAD

**Issue by cartographer1** [62832/MEGACells#118]
Is it a storage bus? Is it a pattern provider? Do I need to connect to directly against the disk drive with bulk storage cells? Is there a throughput limit?

**Comment by 62832** [comment]
See #81. The module is simply a complement to any and all bulk cells on a network with compression cards. It will simply scan every available ME chest and drive for compression-enabled bulk cells and supply crafting patterns to the whole network, while also handling the crafting itself for any compressed variants down to smaller forms when using automation.

You only need one module anywhere on the network for the entire mechanic to be enabled.

**Comment by kylev** [comment]
Playing ATM-10 and finding this in Google resulted in #179.
