### ISSUE TITLE
MEGA Chemical Cells stacking beyond 1

### ISSUE THREAD

**Issue by gjmhmm8** [62832/MEGACells#119]
![image](https://github.com/62832/MEGACells/assets/73775469/61f4b6ec-e94f-4910-92d5-bf947eff51c5)
'64x megacells:chemical_storage_cell_64m'

**Comment by 62832** [comment]
I don't know what this is supposed to mean.

**Comment by 62832** [comment]
@gjmhmm8 Would you mind telling me which version of MEGA this is on?

**Comment by gjmhmm8** [comment]
mega 2.3.3 
app mek 1.4.2

**Comment by gjmhmm8** [comment]
ae2 15.1.1

**Comment by gjmhmm8** [comment]
This could lead to resource farming.
