### ISSUE TITLE
Cannot store more than 0x7FFFFFFF mana

### ISSUE THREAD

**Issue by MaxQi233** [62832/MEGACells#120]
Minecraft Version
1.20.1

Forge Version
47.2.20

Mod Version
MEGA Cells：2.3.6
AE2：15.1.1
Applied Botanics：1.5.0

![ae里的魔力](https://github.com/62832/MEGACells/assets/59874619/97f14aea-ff9b-400c-bb70-95a4aba6813a)

![魔力存储元件](https://github.com/62832/MEGACells/assets/59874619/6d7da1dc-1e43-4823-9a62-ffa78a8f7dda)

As shown in the above images, when the mana grows to 2147483647 (0x7FFFFFFF), it no longer grows, and there is still space left in the storage cell.

**Comment by 62832** [comment]
This may be a limitation with Applied Botanics itself, or even Botania due to the fact that Botania only supports `int` capacities for mana storage. I would advise also opening this issue on the Applied Botanics repo.

**Comment by MaxQi233** [comment]
Okay, thank you for your reply. I will try to provide feedback on this issue to Botania and Applied Botanics. However, there may not be a response as they only support 256k components. 
If they don't consider changing the data type, will MEGA CELLS consider removing these overly large mana storage cells?

**Comment by MaxQi233** [comment]
![QQ截图20240505193205](https://github.com/62832/MEGACells/assets/59874619/468ea838-c9dc-44a2-8cd9-3d36a56d30bd)

Look at this. I don't think vazkii will change the data type. Lol. 
Okay, okay, I'll use multiple small-sized cells instead. Thanks for your reply again. :)

**Comment by MaxQi233** [comment]
Correction: 
The total amount of mana in the entire ME network is limited by int type, and using multiple cells is not useful.

**Comment by 62832** [comment]
> Okay, thank you for your reply. I will try to provide feedback on this issue to Botania and Applied Botanics. However, there may not be a response as they only support 256k components. If they don't consider changing the data type, will MEGA CELLS consider removing these overly large mana storage cells?

Possibly. If it turns out they're not that useful to have given the limitation, I see no reason to really go beyond 256k. Unless there is some way to use a long internally just for AppBot, I might just omit integration altogether from 1.20.4 onwards.

**Comment by ramidzkh** [comment]
Hey, Applied Botanics developer here. Are you using fluix mana pools? Those have limits at 2147483647, but from my testing using normal import busses on mana pools or other ways of importing mana into cells seems fine.

**Comment by MaxQi233** [comment]
> Hey, Applied Botanics developer here. Are you using fluix mana pools? Those have limits at 2147483647, but from my testing using normal import busses on mana pools or other ways of importing mana into cells seems fine.

I did as you said and it works. Thank you.
