### ISSUE TITLE
1.20.1 - Neoforge 105 Broke Block hardness [2.4.2]

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [62832/MEGACells#121]
I am just removing this mod but just so you know this mod broke diamond deepslate interaction

**Comment by Zeitheron** [comment]
Megacells is trying to load a non-existing block into tag, causing it to fail and cascade-fail all mods:
```
Couldn't load tag minecraft:mineable/pickaxe as it is missing following references: 
	megacells:mega_emc_interface (from megacells-forge-2.4.2-1.20.1.jar)
```

**Comment by Zeitheron** [comment]
Rolling back to 2.3.6 fixes the issue as a temporary thing.

**Comment by 62832** [comment]
Sorry, I should have taken this into consideration when adding that bit of optional integration.

**Comment by 62832** [comment]
Would you tell me if 2.4.3 fixes this for you? I can reopen this if not.

**Comment by P3rf3ctXZer0** [comment]
I will test it
