### ISSUE TITLE
MEGA Cells have an incorrect byte count.

### ISSUE THREAD

**Issue by ShadowFox88** [62832/MEGACells#124]
I have a 64k fluid storage cell, and a 256M mega fluid cell, and the same amount of fluid only takes up 63344/65536 Bytes on the 64k cell, but takes up 2159984/268435456 Bytes. Since they are both holding the same amount of fluid, shouldn't they both take up the same amount of storage on the cell?

Info:
All Of Fabric 7: 2.2.3
MEGA Cells: 2.3.6

https://github.com/62832/MEGACells/assets/66386770/452400fa-325f-49a4-9cb5-9bbb6551370a

**Comment by 62832** [comment]
No, they shouldn't. This is explained [in AE2's own guide](https://guide.appliedenergistics.org/1.20.4/ae2-mechanics/bytes-and-types).

The way that AE2 storage cells work in general is that every new type introduced to its storage has an upfront cost proportional to the total capacity of the cell, that being 1/128 of the capacity in bytes.
