### ISSUE TITLE
Compression Card messes up item counts in terminals

### ISSUE THREAD

**Issue by KiARC** [62832/MEGACells#125]
When a Bulk Storage Cell with a Compression Card is filled with, for example, 100k gold ingots, a crafting terminal only displays a handful, but extracting from that stack does provide access to all of the items. There is a Decompression Module on the network. This does not occur without the Compression Card.

**Comment by 62832** [comment]
That is the entire point. This is to prevent issues caused by existing approaches such as compacting drawers reporting more items than are actually available in storage, which throws off things like auto-crafting.

**Comment by KiARC** [comment]
Ah, got it. Perhaps that should be documented somewhere more clearly (maybe in the description text of the compression card?)

**Comment by 62832** [comment]
I plan on eventually writing a proper guide for MEGA as a whole to include within the in-game AE2 guide. This will be one of the things to clarify there.

**Comment by KiARC** [comment]
Good idea. Maybe add it in the same way that AE2 and other mods like the one with extended inscribers (I wish I could remember the name, AE2Extra maybe?) do for consistency in the interface. Also, it looks like the incorrect value getting presented does in fact break auto crafting (it says "not enough available" and displays the incorrect amount shown in the terminal) even if there's a decompression module available, but maybe I've just set something up wrong. Does the priority of the decompression module need to be anything specific or something?
