### ISSUE TITLE
crafting patterns and mega pattern providers

### ISSUE THREAD

**Issue by irbala** [62832/MEGACells#128]
crafting patterns cannot be slotted into mega pattern providers

![image](https://github.com/62832/MEGACells/assets/69251661/b6648055-cc6c-4c27-8805-37303e2335a1)
 
kindly help with it i need to to automate crafting on my server

thank you

**Comment by 62832** [comment]
This is intentional. MEGA Pattern Providers are supposed to only accept processing patterns.
