### ISSUE TITLE
i don't know how the mega interface works.

### ISSUE THREAD

**Issue by blokjeblok111** [62832/MEGACells#130]
hello can anyone help me with the mega interface pls, i don't know how it works.

**Comment by 62832** [comment]
Do you know how the regular ME Interface works?

**Comment by blokjeblok111** [comment]
> Do you know how the regular ME Interface works?

Yes i know how me works

**Comment by 62832** [comment]
So where's the confusion then? The MEGA Interface works identically, but has more slots.

**Comment by blokjeblok111** [comment]
> So where's the confusion then? The MEGA Interface works identically, but has more slots.

The last time i tried it it didn’t work

**Comment by blokjeblok111** [comment]
It didn’t do anything

**Comment by 62832** [comment]
What version are you playing on and what do you mean "it didn't do anything"?

**Comment by blokjeblok111** [comment]
> What version are you playing on and what do you mean "it didn't do anything"?

I’m playing 1.20.1 and it didn’t do anything like i put items in it to craft but it didn’t craft

**Comment by 62832** [comment]
What do you mean "you put items in to craft"? The Interface doesn't craft anything unless it has a Crafting Card.

Are you sure you know what you're talking about?

**Comment by blokjeblok111** [comment]
> What do you mean "you put items in to craft"? The Interface doesn't craft anything unless it has a Crafting Card.
> 
> Are you sure you know what you're talking about?

Yes and it had a crafting card

**Comment by 62832** [comment]
Okay, well, the MEGA Interface is functionally identical to the ME Interface in every way apart from the increase in config and storage slots. There shouldn't be any issue with it that the ME Interface wouldn't also have. Check if you're not doing something wrong like trying to use it without a channel.

**Comment by blokjeblok111** [comment]
> Okay, well, the MEGA Interface is functionally identical to the ME Interface in every way apart from the increase in config and storage slots. There shouldn't be any issue with it that the ME Interface wouldn't also have. Check if you're not doing something wrong like trying to use it without a channel.

Okay but i just tried it again and it worked so i think its fixed, and i’m sorry to bother you
