### ISSUE TITLE
Feature Request: Cross-Subnet Decompression Module

### ISSUE THREAD

**Issue by Tzalumen** [62832/MEGACells#134]
This is my current configuration:
autocrafting subnet with CPUs, pattern provider, furnace 
storage bus
interface
Main system
storage bus
interface
subnet
storage bus
interface
subnet with bulk drive, compression enabled, full of compressed sand

as it stands right now, attaching a decompression module to any of these subnets will not allow the crafting CPUs on the autocrafting subnet to execute a recipe request to craft glass

Would it be possible to configure the decompression module to enable those crafting recipes, either by connecting one to the requesting subnet, or one to the storage subnet?

**Comment by 62832** [comment]
Feasibly, no. I invite you to read through #93 for a brief rationale as to why this wouldn't be possible.
