### ISSUE TITLE
[Feature Request] Readd the me cell dock

### ISSUE THREAD

**Issue by micrwvae** [62832/MEGACells#137]
mentioned it in the discord as well some time ago
would be nice if you could add it back before it gets implemented in the base mod

**Comment by AngelTechnic** [comment]
what version of MEGA Cells are you using? in all the version of it i'm using (on 1.20.1), it's there

**Comment by 62832** [comment]
You realise that isn't the most recent available version of it, right? This issue was opened with 1.21+ in mind.
