### ISSUE TITLE
Induction Card from Applied Flux is incompatible with MEGA Interfaces and Pattern Providers

### ISSUE THREAD

**Issue by James103** [62832/MEGACells#138]
When MEGA Cells and Applied Flux are both installed, the Induction Card added by Applied Flux is incompatible with MEGA Interfaces and MEGA Pattern Providers. The card is compatible with regular Interfaces and Pattern Providers, as well as their extended versions from ExtendedAE.

To test, craft several Induction Cards and try to place one in a regular Interface, an extended Interface, and a MEGA Interface. The first two will allow the card to go in, while the MEGA Interface will reject the card.

Minecraft 1.20.1
Forge 47.3.0
AE2 15.2.11
Applied Flux `1.20-1.1.8-forge`
ExtendedAE `1.20-1.1.12-forge`
MEGA Cells `2.4.4-1.20.1`
Mod pack: [Project Architect 2](https://www.curseforge.com/minecraft/modpacks/project-architect-2) version 3.2

**Comment by turnerlewis** [comment]
Came here to report this, glad someone else did. +1

**Comment by turnerlewis** [comment]
The mod ExtendedAE adds Extended Pattern Provider, which does a better job for those who want a solution in existing modpacks!
