### ISSUE TITLE
Mod Incompatibility with ArsEng and MEGACells

### ISSUE THREAD

**Issue by 54RG3NTM4YH3M** [62832/MEGACells#143]
I have the mods ArsEng , MEGACells  in a modpack of about 300 mods with  Ars Neuvo and Applied Energistics 2  in the modpack and whenn I started the modpack the following error was produced,

>"` java.lang.NoSuchMethodError: 'void gripe._90.arseng.item.SourceCellItem.<init>(net.minecraft.world.item.Item$Properties, appeng.items.storage.StorageTier, net.minecraft.world.level.ItemLike)' `"

 
This is the crash report for the error:
[crash-2024-09-27_14.45.28-fml.txt](https://github.com/user-attachments/files/17162451/crash-2024-09-27_14.45.28-fml.txt)

**Comment by 62832** [comment]
Your version of Ars Énergistique is out of date. Check again and see what the latest version of that actually is.
