### ISSUE TITLE
MEGA Radioactive Chemical Storage Cell is incompatible with Spent Nuclear Waste 

### ISSUE THREAD

**Issue by Pokepants** [62832/MEGACells#144]
As the title says.

Works fine with Nuclear Waste, Polonium and Plutonium

Is this a feature or a bug?

Playing Cafetoria 1.3.2 .
![image](https://github.com/user-attachments/assets/14c9a28f-eaee-47be-986f-ce9c42d82da1)

**Comment by 62832** [comment]
This is a feature. You can selectively enable support for Spent Nuclear Waste via a config option.

**Comment by AngelTechnic** [comment]
> As the title says.
> 
> Works fine with Nuclear Waste, Polonium and Plutonium
> 
> Is this a feature or a bug?
> 
> Playing Cafetoria 1.3.2 . ![image](https://private-user-images.githubusercontent.com/36905111/372305384-14c9a28f-eaee-47be-986f-ce9c42d82da1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2ODUyNjIsIm5iZiI6MTcyODY4NDk2MiwicGF0aCI6Ii8zNjkwNTExMS8zNzIzMDUzODQtMTRjOWEyOGYtZWFlZS00N2JlLTk4NmYtY2U5YzQyZDgyZGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDIyMTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MzBlNTYxZjI0MGVhNzgzMWZlYjlhNTdiMjE3ZTJlZjMwZjE0MGM4OTAxZmM0ZDZhYTkxYmNjZmYzYWVjZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bCZEKhAHReZwZqaQCn-0diacgfW7IqTZN6OW5WRjSa8)

If you want to deal with your spent nuclear waste, the best way to do it is to have a storage bus with max priority, partitioned for spent nuclear waste, and attached to the top or bottom of a Mekanism radioactive waste barrel. Then use some form of chemical transfer to distribute this waste to a bunch of other barrels to increase the rate of decay (Gas Pipez are the best at this in my experience)
