### ISSUE TITLE
Client won't launch when updated and curse forge mods client side is bugged

### ISSUE THREAD

**Issue by Zelioth** [62832/MEGACells#15]
Not sure if it's something to do with how you uplodaed it but even when I have 1.4.1 installed on the versions page in the curse forge launcher it shows that 1.3.1 is installed. 

but 1.4.1 won't allow the client to launch when installed so unsure why. doesn't show up in log or create crash report

MC 1.19.2
Forge 43.1.38
Mega Cells 1.4.0 and 1.4.1

**Comment by 62832** [comment]
Do you have any other mods installed that I should know about? e.g. what version of AE2 are you running MEGA with?

**Comment by Zelioth** [comment]
AE2 is on version 12.7.0 and probably We have over 387 mods. It works fine on version 1.3.1 but the 1.4 versions does not function

**Comment by 62832** [comment]
Ah, that might be because I rushed to set the minimum required version for 1.4+ to be the 12.7.2 hotfix rather than 12.7.0. Is updating AE2 on your end an option or should I go ahead and bump that requirement back down?

**Comment by 62832** [comment]
You should be using AE2 12.8.2 or higher for 1.4 builds to work.
