### ISSUE TITLE
NeoForge 1.21.1 Mega Cells Error on startup

### ISSUE THREAD

**Issue by Zelioth** [62832/MEGACells#151]
Minecraft 1.21.1
NeoForge 21.1.85
Mega Cells 4.2.0
AE2 19.0.25

Appears to be some sort of issue with mega cells when on the latest neoforge versions . Multiple versions even. I ran it up in a controlled environment of just AE2 and mega Cells. If you run it up next to other mods it will give a different error reporting a config error but when running up solo it causes all these errors 

![image](https://github.com/user-attachments/assets/6f5c2bed-ecd1-4fa7-9333-60793da25c44)
[crash-2024-12-09_13.47.30-fml.txt](https://github.com/user-attachments/files/18067299/crash-2024-12-09_13.47.30-fml.txt)
[latest.log](https://github.com/user-attachments/files/18067300/latest.log)

**Comment by 62832** [comment]
This is simply due to MEGA not yet being updated to work with the latest release of AE2. Have patience.
