### ISSUE TITLE
Compression card for all MEGA cells.

### ISSUE THREAD

**Issue by xtended2l** [62832/MEGACells#155]
Any chance you could make compression card support all MEGA cells? I mean there are a lot of materials, which are not actually bulk items, but they exist as nuggets, ingots and blocks. From the other hand - these ingots do not need infinity space. So it would be great to keep them in ordinary cells. Even if item slot, will start taking for example 3 types for having nugget, ingot and block in one slot. It is still better, than all other options:
1. Using Storage Drawer - which is cheap but we know downsides - takes 1 block space for only 1 item and shows incorrect number in the system.
2. Store nuggets, ingots and blocks in 3 different slots, and add patterns to compress and decompress, which is obviously inconvenient.
3. Using MEGA bulk cell, even for non-bulk, i.e. small amount of items only for the sake of conversion, which is still best option from what we have.

So, for 63 type cells - we will receive 21 3-tier bulk slots. Please tell me it is possible :)

**Comment by 62832** [comment]
Not possible. The entire compression mechanic can only work _because of_ the bespoke cell inventory used by bulk cells.
