### ISSUE TITLE
MEGA Crafting Co-Processing Unit In-World Transformation only requires regular Crafting Unit

### ISSUE THREAD

**Issue by Maiklaww** [62832/MEGACells#156]
In ATM10 2.6 with MEGA Cells 4.2.1, I have found a reproduceable case where a regular Crafting Unit when right-clicked with an Engineering Processor turns into a MEGA Crafting Co-Processing Unit.

The expected behaviour would require a MEGA Crafting Unit to be right-clicked with an Engineering Processor.

**Comment by 62832** [comment]
This was fixed in a previous (unreleased) commit, but I've had to do some more work on this to also ensure that upgrading to either co-processor in general was possible again.
