### ISSUE TITLE
1.19.2 - Crashes with latest ``appliedenergistics2-forge-12.8.3-beta``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [62832/MEGACells#16]
Sorry it needs to update again :( I feel ya though as I upkeep a modpack on 2 platforms. Crashes for sure server side but I am sure it would crash on load in SP. 

Forge 43.1.43
Mod MEGACells-1.4.2-1.19.2 + appliedenergistics2-forge-12.8.3-beta

**Comment by 62832** [comment]
Yeah, I made a small change to an implementation detail in AE2 itself but I am again waiting on dev builds since the usual repo that AE2 uses for those is having storage issues. I'll have a hotfix out as soon as possible.

**Comment by 62832** [comment]
Fixed in version 1.5.0.
