### ISSUE TITLE
1.19.2 in large pack updates still do not work

### ISSUE THREAD

**Issue by Zelioth** [62832/MEGACells#18]
Howdy, 
Creator and Dev. of Friends United. I am trying to update the mod from 1.3.1 which allows the pack to launch to all versions above. Each version above will not allow the pack to launch. The pack will go from the play button to just not appearing at all. If you downgrade to 1.3.1 the pack will work perfect. 

ModPack : Friend United 2.2.1 https://www.curseforge.com/minecraft/modpacks/friends-united
Mod count 398
Minecraft 1.19.2
Forge 43.1.43
MEGA CELLS 1.3.1
Versions Tested 1.4.0 to 1.5.1

[debug.log](https://github.com/62832/MEGACells/files/9795372/debug.log)
[latest.log](https://github.com/62832/MEGACells/files/9795373/latest.log)

It does not generate a crash report because it doesn't necessarily crash. just not launch

**Comment by 62832** [comment]
Update your version of AE2 as per the changelogs for all those tested versions. 1.5+ requires 12.8.3-beta specifically.

**Comment by Zelioth** [comment]
OH They are listing them as Beta so they weren't showing up in my update log or my Excel Doc as a change was made on their URL for "Release" thank you, Sorry about that.
