### ISSUE TITLE
Crashes with latest fabric version

### ISSUE THREAD

**Issue by Poke097** [62832/MEGACells#21]
appliedenergistics2-fabric-12.8.4.jar crashes with latest megacells-fabric-1.5.1-1.19.2.jar

**Comment by Poke097** [comment]
[crash.txt](https://github.com/62832/MEGACells/files/9892645/crash.txt)

**Comment by 62832** [comment]
Still working on a hotfix, though it should be almost finished by now.

**Comment by Poke097** [comment]
Any ETA?

**Comment by 62832** [comment]
Once Applied Mekanistics has updated over on Forge with a hotfix of its own so I can push it to both loaders at once.

**Comment by 62832** [comment]
Fixed in v1.5.3.
