### ISSUE TITLE
Does radioactive cell works at 1.18?

### ISSUE THREAD

**Issue by Goufix** [62832/MEGACells#26]
I tried to use radioactive cell, but it doesn't work.

A superficial code inspect give me a hypothesis
`MEGAChemicalCell` implementation is kinda different from `MEGARadioactiveCell` one.
I think that it should be the same, with inverted filter, AIR?

**Comment by Goufix** [comment]
I thought of something like this:

```java
public class MEGARadioactiveCell extends MEGAStorageCell {
    public MEGARadioactiveCell(Properties properties) {
        super(properties.stacksTo(1), MEGATier._256M, AppMekCellType.CHEMICAL);
    }

    public void appendHoverText(ItemStack is, Level level, List<Component> lines, TooltipFlag advancedTooltips) {
        addCellInformationToTooltip(is, lines);
    }

    @Override
    public boolean isBlackListed(ItemStack cellItem, AEKey requestedAddition) {
        if (requestedAddition instanceof MekanismKey key) {
            // blacklist anything radioactive
            return ChemicalAttributeValidator.DEFAULT.process(key.getStack());
        }
        return true;
    }
}
```

**Comment by 62832** [comment]
Not how it works in the slightest. The radioactive cell uses its own custom inventory and handler altogether and requires you to filter it in advance with the chemical you want it to hold, similarly to the Bulk Item Cell.
