### ISSUE TITLE
Radioactive Cell, when filled with a radioactive material, should be a proper radiation hazard.

### ISSUE THREAD

**Issue by James103** [62832/MEGACells#30]
Currently (as far as I can tell), entities do not get irradiated solely through the carrying of a filled MEGA Radioactive Chemical Storage Cell, regardless of the amount or type of chemical inside (including radioactive chemicals).

Idea: At least for players, if a player has a MEGA Radioactive Chemical Storage Cell in their inventory, and that cell currently contains some radioactive chemical, and the player is not wearing a Hazmat Suit or equivalent, then the player is irradiated a small amount every second (or tick) based on the radioactive chemical the cell is currently holding and the amount of that chemical.

A full cell of nuclear waste should be enough to cause radiation poisoning within a couple of hours in a player's inventory (IGT or RTA, depending on how Mekanism calculates time), with multiple cells and more radioactive chemicals speeding that up.

If the cell or the drive the cell is in is somehow destroyed (burned, exploded, cactus, etc), it should instantly release radiation in an area proportional to the amount of radioactive material that was present in the cell or drive, similar to if a pipe or waste barrel that held radioactive material was broken.

**Comment by 62832** [comment]
Will take into consideration. I've already been somewhat unhappy with the balancing for this cell and am hoping to rework it as part of the 2.0.0 release. This should be part of that rework for sure.

**Comment by Sakata-MC** [comment]
Thing is, the molecules are being stored as digital data, 1's and 0's. So they aren't radioactive.
If it was 'balanced', being near any drive with contents that have a mass above lead would instantly kill you due to the sheer density.

**Comment by 62832** [comment]
I completely forgot this issue even existed.
