### ISSUE TITLE
MEGA Fluid cells not accepting cards.

### ISSUE THREAD

**Issue by KodYazanDruid** [62832/MEGACells#33]
I am playing on Forge.
![2022-12-18_19 48 45](https://user-images.githubusercontent.com/45048634/208309996-161e9991-bde8-4040-a65b-b7819059fef6.png)

Normal fluid cells acceps equal distribution, overflow cards but MEGA fluid cells not.

**Comment by 62832** [comment]
Has been fixed in dev already, but I'll leave this open until the fix is actually released as part of 2.0.0. Thanks for bringing it to attention still.

**Comment by 62832** [comment]
Fixed in 2.0.0-beta.0. If I'm misremembering let me know ASAP.
