### ISSUE TITLE
Crash with version 2.0.0 on Forge 1.19.2

### ISSUE THREAD

**Issue by lamoyrl90** [62832/MEGACells#36]
https://pastebin.com/0JFiSGk3

I think there's a missing check as to whether the mod should register the mana cells. No Botania in this instance. I'll add Botania to see if it fixes it.

**Comment by lamoyrl90** [comment]
Yep, loads without issue with Botania and Applied Botanics installed

**Comment by 62832** [comment]
Shit, yeah, it seems I messed something up with the conditional init. I'll have a hotfix out for this later today.

**Comment by 62832** [comment]
Should be fixed now in 2.0.0-beta.2. If not, let me know if it persists.
