### ISSUE TITLE
Block idea: MEGA Interface, an upgraded version of the ME Interface

### ISSUE THREAD

**Issue by James103** [62832/MEGACells#39]
Functions identically to the ME Interface from the base mod, except with 18 slots to send/receive items instead of just 9. This allows for slightly more compact setups and more efficient channel usage.

No such block currently exists in this mod, but the idea was brought up to match the ME Pattern Provider.

**Comment by 62832** [comment]
Will consider. This was suggested prior as a companion to things like bulk cell compression in order to keep all available variants in stock if using a "compressed blocks" mod, which adds up to 12 different variants for some compression chains.
