### ISSUE TITLE
Error when using the MEGA Cells mod in Minecraft with Texture

### ISSUE THREAD

**Issue by vindocel** [62832/MEGACells#40]
Hello,

I am writing to report an error that I have encountered while using your mod "MEGA Cells" in Minecraft. The error message I received is as follows:

"**net.minecraftforge.fml.ModLoadingException:** MEGA Cells (megacells) encountered an error during the done event phase"

"**java.lang.IllegalStateException:** Render layers can only be set during client loading! This might ideally be done from **FMLClientSetupEvent.**"

This error occurred when I was rendering the overlay in the game. I have attached the Minecraft crash report for your reference.

I would greatly appreciate it if you could investigate this issue and provide a solution as soon as possible. I have been really enjoying using your mod, and I hope that this problem can be resolved so I can continue to use it.

Thank you for your time and efforts.

- I would like to add that this error occurred when I was trying to start the mod using the **[Dark-Everywhere v1.3.9🌙](https://github.com/vindocel/Dark-Everywhere/releases/tag/v1.3.9)** texture pack, and I have tested it on a clean installation of minecraft,

- "I also wanted to note that this texture pack uses a GLSL shader system to color the text of container titles, so this error may be related to how the mod interacts with the shader system."

Sincerely,
[[Victor Matos ](https://github.com/vindocel)]

[crash-2023-01-25_08.12.00-client.txt](https://github.com/62832/MEGACells/files/10498745/crash-2023-01-25_08.12.00-client.txt)

**Comment by 62832** [comment]
Can't say I'm experiencing the same problem in either a development or release environment, and the code being referenced is only run during a client-specific event anyways. I'm happy to double-check later though if you have any other steps to reproduce that might be helpful to know about.

**Comment by 62832** [comment]
Nevermind, indeed it turns out I wasn't using the proper event for it. Sorry about that. Hotfix should be out in a bit.
