### ISSUE TITLE
Drives filling up really fast?

### ISSUE THREAD

**Issue by Adzeiros** [62832/MEGACells#41]
I might be doing something wrong, but I have a 256m item drive, and I only have about 1,000 to 2,000 items in my system and the drive is already like half full? Is that right? I feel like these drives should be storing MILLIONS of items, not like 1-5 thousand.

**Comment by 62832** [comment]
They should be, and they are.

The byte counts are just a result of how AE2 calculates used space in bytes: Each *new* type you introduce takes up 1/256th of the total space on any "basic" storage cell, with subsequent items of that type then being 8 items per one byte.
