### ISSUE TITLE
MEGA Pattern Provider issue

### ISSUE THREAD

**Issue by werl** [62832/MEGACells#44]
This only occures on the multi-block version and not the single block. Works fine otherwise. Tested in SMP and SSP.

ATM8 1.0.10
MEGACells version 2.0.0b7 (forge)
Forge 43.2.3

![MEGAPatternProviderBug](https://user-images.githubusercontent.com/1848345/217394535-4476eb6e-79cd-42f8-ae5d-ef6cb8b637c5.png)

**Comment by taj1994** [comment]
I have this issue as well. Also ATM 8 1.0.10, with the same Forge and mod versions

The full block version displays the pattern slots properly in two rows, while the panel version displays them as one long row
![image](https://user-images.githubusercontent.com/1844822/218870802-bec4b38d-ca08-40af-8f18-19cb262aba8a.png)
![image](https://user-images.githubusercontent.com/1844822/219503339-3df53669-0081-4854-b2b8-f5a4664c0231.png)

**Comment by 62832** [comment]
Sorry for the late response. I believe I've fixed this in the latest commit; turns out I had forgotten to attach the appropriate menu to the part version as well. 😅

**Comment by 62832** [comment]
I've pushed a build out now which includes this patch. Should hopefully be out within the next 20 minutes.
