### ISSUE TITLE
Compressed items cannot be requested via auto crafting options

### ISSUE THREAD

**Issue by aria1th** [62832/MEGACells#45]
Compressed, block-form items are unpacked when player manually requests it, but cannot be requested when auto crafting plan tries to use it, and will cause missing item error without actually showing what is missing.

**Comment by 62832** [comment]
I'll be working on this in the coming days, since I had plans for an auto-decompression mechanic to address this but took a small impromptu hiatus. Hopefully it shouldn't be too long of a wait.
