### ISSUE TITLE
ru_ru.json

### ISSUE THREAD

**Issue by FunnHik228** [62832/MEGACells#47]
`{
  "itemGroup.megacells": "MEGA CELLS",

  "item.megacells.mega_item_cell_housing": "Корпус для предметной ячейки",
  "item.megacells.mega_fluid_cell_housing": "Корпус для жидкостной ячейки",
  "item.megacells.mega_chemical_cell_housing": "Корпус для химической ячейки",
  "block.megacells.mega_crafting_unit": "Блок создания",

  "item.megacells.cell_component_1m": "1M Компонент хранения",
  "item.megacells.cell_component_4m": "4M Компонент хранения",
  "item.megacells.cell_component_16m": "16M Компонент хранения",
  "item.megacells.cell_component_64m": "64M Компонент хранения",
  "item.megacells.cell_component_256m": "256M Компонент хранения",

  "item.megacells.item_storage_cell_1m": "1M Предметная ячейка хранения",
  "item.megacells.item_storage_cell_4m": "4M Предметная ячейка хранения",
  "item.megacells.item_storage_cell_16m": "16M Предметная ячейка хранения",
  "item.megacells.item_storage_cell_64m": "64M Предметная ячейка хранения",
  "item.megacells.item_storage_cell_256m": "256M Предметная ячейка хранения",

  "item.megacells.fluid_storage_cell_1m": "1M Жидкостная ячейка хранения",
  "item.megacells.fluid_storage_cell_4m": "4M Жидкостная ячейка хранения",
  "item.megacells.fluid_storage_cell_16m": "16M Жидкостная ячейка хранения",
  "item.megacells.fluid_storage_cell_64m": "64M Жидкостная ячейка хранения",
  "item.megacells.fluid_storage_cell_256m": "256M Жидкостная ячейка хранения",

  "item.megacells.chemical_storage_cell_1m": "1M Химическая ячейка хранения",
  "item.megacells.chemical_storage_cell_4m": "4M Химическая ячейка хранения",
  "item.megacells.chemical_storage_cell_16m": "16M Химическая ячейка хранения",
  "item.megacells.chemical_storage_cell_64m": "64M Химическая ячейка хранения",
  "item.megacells.chemical_storage_cell_256m": "256M Химическая ячейка хранения",

  "item.megacells.bulk_cell_component": "Комонент для массового хранения",
  "item.megacells.bulk_item_cell": "Ячейка для для массового хранения",

  "item.megacells.radioactive_cell_component": "Компонент радиоактивного хранилища",
  "item.megacells.radioactive_chemical_cell": "Радиоактивных ячейка хранения",

  "item.megacells.portable_item_cell_1m": "1M Переносная предметная ячейка",
  "item.megacells.portable_item_cell_4m": "4M Переносная предметная ячейка",
  "item.megacells.portable_item_cell_16m": "16M Переносная предметная ячейка",
  "item.megacells.portable_item_cell_64m": "64M Переносная предметная ячейка",
  "item.megacells.portable_item_cell_256m": "256M Переносная предметная ячейка",

  "item.megacells.portable_fluid_cell_1m": "1M Переносная жидкостная ячейка",
  "item.megacells.portable_fluid_cell_4m": "4M Переносная жидкостная ячейка",
  "item.megacells.portable_fluid_cell_16m": "16M Переносная жидкостная ячейка",
  "item.megacells.portable_fluid_cell_64m": "64M Переносная жидкостная ячейка",
  "item.megacells.portable_fluid_cell_256m": "256M Переносная жидкостная ячейка",

  "item.megacells.portable_chemical_cell_1m": "1M Переносная химическая ячейка",
  "item.megacells.portable_chemical_cell_4m": "4M Переносная химическая ячейка",
  "item.megacells.portable_chemical_cell_16m": "16M Переносная химическая ячейка",
  "item.megacells.portable_chemical_cell_64m": "64M Переносная химическая ячейка",
  "item.megacells.portable_chemical_cell_256m": "256M Переносная химическая ячейка",

  "block.megacells.mega_energy_cell": "Сверхплотный энергетический элемент",

  "item.megacells.greater_energy_card": "Большая энергетическая карта",

  "block.megacells.1m_crafting_storage": "Хранилище для изготовления на 1M",
  "block.megacells.4m_crafting_storage": "Хранилище для изготовления на 4M",
  "block.megacells.16m_crafting_storage": "Хранилище для изготовления на 16M",
  "block.megacells.64m_crafting_storage": "Хранилище для изготовления на 64M",
  "block.megacells.256m_crafting_storage": "Хранилище для изготовления на 256M",
  "block.megacells.mega_crafting_accelerator": "Блок создания",
  "block.megacells.mega_crafting_monitor": "Монитор создания"
}
`

**Comment by 62832** [comment]
Why is this an issue and not a pull request?
