### ISSUE TITLE
[1.18.2 - MEGACells-1.3.0] - Crashed with AEAdditions-1.18.2-3.1.0.jar

### ISSUE THREAD

**Issue by realTIMematrix** [62832/MEGACells#5]
Hi,

i created a issue on the other mod, because the error message says that AEAdditions produces the error. But this error appear only after upgrading from MEGACells 1.2.1 to 1.3.0

Here is the link to the other issue with all details.

#https://github.com/the9grounds/AE-Additions/issues/77

Maybe you can have a look too.

**Comment by 62832** [comment]
Odd, I have no idea what could go wrong since the reference to `CELL_COMPONENT_1M` is still the same. All that changed in that regard is where the `ItemDefinition` class used for all the items sits within the project.

**Comment by realTIMematrix** [comment]
Problem was fixed from AEAdditions Mod Author
