### ISSUE TITLE
Bulk storage compression card

### ISSUE THREAD

**Issue by LoffyLV** [62832/MEGACells#50]
![image](https://user-images.githubusercontent.com/76730419/227733034-4b635ea4-908e-4905-ad00-535b4daa5430.png)
If you use compression card in bulk storage cell it says enough material available, but throws out insufficient material error.

**Comment by LoffyLV** [comment]
megacells-forge-2.0.0-beta.7 version
ATM8 pack

**Comment by 62832** [comment]
Duplicate of #42.
