### ISSUE TITLE
MEGA Pattern Provider doesn't rotate properly on the client side

### ISSUE THREAD

**Issue by Saereth** [62832/MEGACells#51]
originally reported here:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3027

Basically it always shows as pointing north despite the actual rotation.

MC 1.19.2
Forge 43.2.6
megacells-forge-2.0.0-beta.8-1.19.2

**Comment by 62832** [comment]
This isn't to do with the blockstate definition, but with AE2's mechanism for rotations pre-1.19.3, which is extremely messy and was done away with eventually for good reason. I'll try to see where this might have gone wrong on my end but I can't promise it'll be in a very timely fashion.

**Comment by Saereth** [comment]
it's just visual so honestly not a high priority if it cant be fixed easily, good luck! :p

**Comment by 62832** [comment]
Leaving this reopened until the next release build, but this has now been fixed in dev.
