### ISSUE TITLE
Error loading mods: InvocationTargetException: null

### ISSUE THREAD

**Issue by Yourname942** [62832/MEGACells#53]
Error loading mods:
![image](https://github.com/62832/MEGACells/assets/58750222/fc0e7273-0309-46d1-b77c-2e247b06f53c)

MC 1.19.2
Forge 43.2.11
MEGACells 1.5.2

**crash log:** https://paste.ee/p/rxJk9

**latest log:** https://paste.ee/p/h6ljO

**Comment by 62832** [comment]
Please update to either 1.5.3 or the beta builds for 2.0.0.
