### ISSUE TITLE
MEGA Pattern Provider

### ISSUE THREAD

**Issue by T0pN1ck** [62832/MEGACells#57]
Its possible to rebase the providers pattern so that it works not only with processing patterns?

**Comment by 62832** [comment]
No, and this was never intended to begin with; the tooltip that says it only works for processing patterns has been there throughout its entire existence.

**Comment by T0pN1ck** [comment]
Okay. I have a question then. Why can the molecular assembler send (what it has assembled) to the part version of the pattern provider, but cannot to full version?

(I apologize for the question not related to the provider itself, which is for processing only).
(Very sorry if the question itself is dumb)

**Comment by 62832** [comment]
If you're asking about the MEGA provider specifically, I don't know, and I still wouldn't be providing much support for that use case anyways. If you're asking about AE2's own pattern provider then that's a question for AE2 itself rather than me.
