### ISSUE TITLE
Decompression/ Compression: Thermal Series Nickel does not appear to be 

### ISSUE THREAD

**Issue by Exikle** [62832/MEGACells#59]
It appears that nickel is not registering as a decompress-able/compressible item.

On Version 2.0.0 - 1.92.2

Have used the compression card in the cell workbench on the bulk item storage cell.

Items are currently stored on 2 separate storage cells

Let me know if there's anything else you need.

![image](https://github.com/62832/MEGACells/assets/1643792/ffd073c7-dbf7-42a7-9584-caf6db3efc83)

**Comment by 62832** [comment]
Are you playing some kind of modpack that uses two different types of nickel interchangeably for recipes?

There is the — admittedly premature — assumption for the compression feature that you're playing on a pack with some unification mod that ensures all nugget-ingot recipes give back the nugget or ingot from the same namespace. As in, if you took 9 nuggets of Thermal nickel to turn into an ingot of Thermal nickel, that ingot would then be crafted back specifically into 9 Thermal nickel nuggets.

**Comment by Exikle** [comment]
Its only this particular material, Lead, Silver etc from Thermal appears to be working. All other mods (Botania, Mek, Create, etc) appear to be fine.

**Comment by Exikle** [comment]
In an attempt to fix it without messing witht he mod itself, tried to add AllTheOres mod just to see what would happen which worked. I'm assuming it overrides the FTB recipe or something which allows the decompression module from seeing it.

In theory (at a quick glance), `recipe.getIngredients().size() == 4 || recipe.getIngredients().size() == 9` should've taken care of it but not sure why it doesnt

**Comment by 62832** [comment]
If the different metals and alloys for whatever reason aren't unified in FTB Skies then the discrepancy between recipes could well be the fact that some nugget-ingot-block recipe for nickel could return one form of nickel one way and another form the other way. This would mean that the recipes involving nickel aren't technically "reversible" as you don't get the same form of that metal back from carrying the recipe out both ways.

**Comment by Exikle** [comment]
Yeah that makes perfect sense, I'll look into it a bit to see where but I'll probably close this issue out once i confirmed
