### ISSUE TITLE
Add icons on mouse over of bulk storage cell

### ISSUE THREAD

**Issue by Exikle** [62832/MEGACells#60]
Hello!

Wondering if you can look at possibly getting the icon of the material in the cell added to the bulk storage cell mouse over similar to the MEGA fluid cell. Would be a nice QOL addition.

Keeping the "Partitioned For:" part wold still be good but more for a quick glance?

![image](https://github.com/62832/MEGACells/assets/1643792/1c096d9a-126b-4463-8678-8b031af28c23)
![image](https://github.com/62832/MEGACells/assets/1643792/30c91bed-f7a4-445a-8012-385d7b1b10f7)

**Comment by 62832** [comment]
I can see about doing this for the next potential release.

**Comment by 62832** [comment]
I've included this feature as part of [2.1.0-beta.3](https://github.com/62832/MEGACells/releases/tag/v2.1.0-beta.3).
