### ISSUE TITLE
(De)compress not detecting crafting recipe in ADhoc network

### ISSUE THREAD

**Issue by Exikle** [62832/MEGACells#64]
The network only sees the items itself so if 10 nuggets are in the adhoc, itll compress to one ingot and one nugget but if you craft with it as an ingrediant itll say not enough nuggets

![image](https://github.com/62832/MEGACells/assets/1643792/5675d91f-3029-4fef-9df4-0e677c3867f2)

**Comment by 62832** [comment]
Do you have a decompression module installed on this ad-hoc network?

**Comment by Exikle** [comment]
I do, made a test world to check some stuff and this is my current setup for testing it.

![image](https://github.com/62832/MEGACells/assets/1643792/7499769f-47b0-43d6-aee4-5d1702f7dbdf)

Wondering if maybe the adhoc would need a crafting cpu too
