### ISSUE TITLE
Mega crafting monitors are bugged

### ISSUE THREAD

**Issue by DragonMaster14545** [62832/MEGACells#65]
It is a big modpack so it might be a cross mod problem. When I place a monitor, it is facing in a direction, but once I add a storage to form the CPU it rotates. But when I place it in the directon where the z axis gets higher when moving into that direction(I have no Idea how to know where north is), it stays that direction.

**Comment by DragonMaster14545** [comment]
After building my base and then starting the first recipes I realised that only the texture is wrong, the item gets displayed propperly
![image](https://github.com/62832/MEGACells/assets/114180377/471b2315-0c43-4497-99f3-82531d0b34a1)

**Comment by 62832** [comment]
That is still something of a bug. Is this 1.19 or 1.20?

**Comment by DragonMaster14545** [comment]
1.19.2

**Comment by 62832** [comment]
...huh. The models *should* already be fine on that version, so I'm not entirely sure.

**Comment by DragonMaster14545** [comment]
Idk, I have the newest version of the mod installed

**Comment by 62832** [comment]
Forgot to mention, I ended up releasing a fix for this in 2.0.3.

**Comment by DragonMaster14545** [comment]
Thanks, it works now
