### ISSUE TITLE
Possible issue? 

### ISSUE THREAD

**Issue by Spraro** [62832/MEGACells#68]
I've only played with it for a few days but the MEGA storage cells call for Inscriber Accumulation Presses to make the Printed Accumulation Circuit when using AE2 Autocrafting and even when double is available for the recipe it doesn't recognize it already in the system. Also, I do have Inscribers set up to make every component needed. 
![Capture](https://github.com/62832/MEGACells/assets/143054330/fda562ba-ff0d-46cf-a89f-b2254d950f72)
Edit: Smaller request quantities recognize the amount of Inscriber Accumulation Press but still ask for multiple of them. do they have durability or? The Presses are stacking up inside the Inscriber I have designated for them and the same with the Printed Accumulation Circuit.

**Comment by Spraro** [comment]
So I do have it set up like that, it fills the inscriber too 64 and says it's missing ingredients

**Comment by 62832** [comment]
Do you? The craft shouldn't be requesting the accumulation press unless you specifically encoded a pattern with the press included.

**Comment by Spraro** [comment]
So w/ around 160 inscribers and 40 Providers, I thought I changed them all after realizing this mistake once before w/ regular cells and it looks like it got me again... sorry for the trouble, thank you I appreciate the help! Love the mod too btw
