### ISSUE TITLE
Bulk Item Cell, not transfering

### ISSUE THREAD

**Issue by elijahward** [62832/MEGACells#71]
Good morning, The bulk item cell isn't transferring items to the cell. Old cells work fine, new cell wont fill with anything

**Comment by elijahward** [comment]
ATM9

**Comment by 62832** [comment]
Did you filter the cell in advance?

**Comment by elijahward** [comment]
yes, and tried different items

**Comment by 62832** [comment]
The cell should still accept items, but in general the network will prioritise any cells that already contain the item in question, or cells that happen to come first along any connected drives. Try running the bulk cell through an ME IO Port first to pull out any such stored items from other cells into the bulk one.

**Comment by 62832** [comment]
That said, there did use to be something of a priority such that items that matched the filter or existing contents of the bulk cell would try to go straight to that bulk cell first. I'll add that back in for the next release, but for now, you should be fine using an IO Port first.

**Comment by elijahward** [comment]
I have done the IO port first to pull everything out of the system, Just won't happen. The

**Comment by 62832** [comment]
Alright, I'll just push another patch release then with the re-added cell priority. Let me know if that fixes it.
