### ISSUE TITLE
256M MEGA Storage Component overflows Matter Condenser

### ISSUE THREAD

**Issue by STtraveller** [62832/MEGACells#72]
![2023-09-14_14 36 03](https://github.com/62832/MEGACells/assets/30729416/87ff433b-f7e3-4c2c-83f4-f46f533fd135)
The Matter Condenser shows the negative int limit and does not store any energy.

**Comment by 62832** [comment]
just, uh, use a 64k

**Comment by STtraveller** [comment]
Just a follow up, 64M is working perfectly and it actually works to store excess energy by setting to destroy items than to matter ball/singularity (where 64 item singularity + 256000energy is the max if singularity is set), it can instantly convert to 64 singularity/matter ball by just deducting the corresponding energy from the storage.
![Screenshot 2023-09-26 at 2 07 49 AM](https://github.com/62832/MEGACells/assets/30729416/d53d6a3f-b9a4-49fc-b185-25c2770e8cbe)
