### ISSUE TITLE
MEGA Pattern Provider Missing?

### ISSUE THREAD

**Issue by TheLoneDude** [62832/MEGACells#73]
I installed MEGA Cells onto StoneBlock 3 so I could use MEGA Pattern Providers in my AE2 system, but when I load in and search in REI/JEI, I can't find it. This is 1.18.2, and I've noticed elsewhere that you've said AE2 had changes in 1.19.2, which made me question if it was in this version at all. I attempted to find config files to see if it was disabled by default but was unable to find anything related, which has left me stumped.

_I've attached a screen snip of what appears when searched:_

![image](https://github.com/62832/MEGACells/assets/86646904/5a4c827f-1a43-43d7-b09d-1d659238bab3)

**Comment by 62832** [comment]
The Pattern Provider does not and will not exist in 1.18 versions. It was only made available due to the upstream changes made to AE2 itself within 1.19.
