### ISSUE TITLE
Bulk Item Cell not taking most items 2.1.3

### ISSUE THREAD

**Issue by FallenPumpking** [62832/MEGACells#74]
The bulk item cell will not take most items, Certus crystal/dust included. I noticed a closed issue of this 2 weeks ago but even on the latest version bug persists in the mod pack ATM 9. Using an ME IO Port just instantly moves the cell to the right, yes on the correct settings also tried every combination of settings, without taking any items. 

Mod version:2.1.3
Pack: ATM 9

**Comment by 62832** [comment]
Is the cell filtered in advance?

**Comment by FallenPumpking** [comment]
Yes, it is partitioned in the Cell Workbench before being put in the network.
