### ISSUE TITLE
[Suggestion]add FE energy cells like mana cells.

### ISSUE THREAD

**Issue by CN0001** [62832/MEGACells#75]
add FE energy cells like mana cells [Applied Botanics] so that we can use the network to transfer energy, supply energy to the network  itself or to the machine through interface.

**Comment by 62832** [comment]
I'm not sure whether this is entirely within the scope of MEGA. I'll have to give it some more thought.

**Comment by CN0001** [comment]
你发的信件我已经收到（张继炎）

**Comment by CN0001** [comment]
If this is out of the range, I think you can create a new module to solve this need, this feature is simple but needed!

**Comment by 62832** [comment]
Seeing as the [Applied Flux](https://www.curseforge.com/minecraft/mc-mods/applied-flux) add-on now exists, I am closing this issue.
