### ISSUE TITLE
Not able to import botania mana into AE2 System

### ISSUE THREAD

**Issue by Orrinw01** [62832/MEGACells#78]
Unless I'm doing something completely wrong The AE2 system will not accept mana. I have tried a import bus, a interface, I have tried a mana pump into an interface. Thank you for the help.

**Comment by 62832** [comment]
I don't have enough information to go on here. What does your current setup look like?

**Comment by Orrinw01** [comment]
I'm sorry now that you mention it it is most likely an applied botanics issue, I thought mega added the cells that added the functionality but you are just expanding upon it. Thank you!
