### ISSUE TITLE
[1.20.1] Compression Card Issue

### ISSUE THREAD

**Issue by Cyranos** [62832/MEGACells#81]
Using the compression card on mega bulk cells causes the system to not be able to use the item for auto crafting purposes e.g. if you have iron ingot in a bulk cell with a compression card and try to auto craft iron bars it won't work, remove the card & it will work

Forge Version: 47.2.1
AE2 Version: 15.0.13
Mega Cells Version: 2.1.5-1.20.1

**Comment by 62832** [comment]
This is what the Decompression Module is for.

**Comment by Cyranos** [comment]
I didn't even notice that was a block, my sincerest apologies!
