### ISSUE TITLE
Unable to craft Sky Steel [All of Fabric 7 1.0.2]

### ISSUE THREAD

**Issue by fmbellomy** [62832/MEGACells#94]
Throwing the items necessary to craft Sky Steel into lava just burns them, and doesn't do an in-world transformation.

Not sure if this is a bug on MEGA's behalf, or AOF's, but thought I'd report it here anyway.

**Comment by 62832** [comment]
I'm unable to reproduce this either in dev or with a compiled JAR on a test instance, but I can reproduce this specifically when playing AOF7. I can't say I know what might be causing this apart from some other mod in the pack mixing into the `ItemEntity` class.

**Comment by 62832** [comment]
Turns out this is actually caused by the *Go Fish!* mod having its own mixin for making certain items fireproof, which seems to not be playing too nice with MEGA's own mixin.
