### ISSUE TITLE
Server crashes when submitting crafting jobs involving MEGA decompression module

### ISSUE THREAD

**Issue by rikaakiba** [62832/MEGACells#95]
The pack is ATM9 (0.2.31) comes with MEGA Cells 2.2.7-1.20.1.
Cannot reproduce reliably, but does happen several times a day.

Crash reports:
[crash-2023-12-14_16.57.53-server.txt](https://github.com/62832/MEGACells/files/13675390/crash-2023-12-14_16.57.53-server.txt)
[crash-2023-12-14_17.03.02-server.txt](https://github.com/62832/MEGACells/files/13675391/crash-2023-12-14_17.03.02-server.txt)
[crash-2023-12-15_00.03.03-server.txt](https://github.com/62832/MEGACells/files/13675392/crash-2023-12-15_00.03.03-server.txt)

These 3 crashes above happened when trying to craft 1 256M MEGA Storage Component, but also happened with other recipes in the past.
I have redstone, glowstone, sand and ender pearl stored in MEGA Bulk Item Storage Cells with Compression Card installed and the crafting plan looks something like this:
![image](https://github.com/62832/MEGACells/assets/6128615/f0a91a61-7aff-4ce5-9dac-d9ee2e8c893b)
![image](https://github.com/62832/MEGACells/assets/6128615/f4402335-1ae6-499c-a74c-63260dcc146c)
![image](https://github.com/62832/MEGACells/assets/6128615/fa76d849-4c41-4295-aaa6-2883b985d61a)

**Comment by 62832** [comment]
If more people report this as happening consistently then I'll try to push out a potential fix for it, but for now I am unable to reproduce this on my end.

**Comment by 62832** [comment]
Hi, is this still happening to you in version 2.2.9?

**Comment by rikaakiba** [comment]
Seems like the issue is gone.

I've been using a computercraft script to request a 256m storage component for every 15min~2hr, which should be similar to what i've been doing in the past.
Also requested manually a few times, and the server is running for about 2 days without a single crash.
Compared to before which is like 5 crashes in a day, I think it's probably solved now.

Thank you very much for the help!
