### ISSUE TITLE
[Feature Request] Add MEGA Source Cells

### ISSUE THREAD

**Issue by Ianthasys** [62832/MEGACells#96]
Title pretty much says all. I know you made the Ars Energistique mod, and figured that it'd be nice to have MEGA tier cells much like you did for the Applied Botanics Cells.

Would beg to question who'd need that much source, but then again, who needs that much botania mana?

**Comment by 62832** [comment]
I've been meaning to do this but completely neglected it. I really ought to sort that out.

**Comment by Ianthasys** [comment]
no rush, I had figured you'd just missed it. I've heard you're a busy dude.
