### ISSUE TITLE
Compression and Decompression breaking Auto-Crafting

### ISSUE THREAD

**Issue by Pienapples** [62832/MEGACells#99]
Playing on Minecraft version 1.20.1
Playing Modpack ATM9
Using Bulk Cell with a Compression Module and a Decompression Module on the same Network, trying to Autocraft a "Functional Storage" Diamond Upgrade and it gives me a crazily weird crafting request to be able to make it. [Here's the request.](https://imgur.com/a/ypHC4DP)

There is a recipe in the system for making Gold Ingots, removing it, changing it, etc. has no effect on the craft request.

**Comment by 62832** [comment]
Shall I assume this has long been resolved by the priority feature on the decompression module?
